### ISSUE TITLE
[Textos Notary] - Bitregistro A ser Pago

### ISSUE THREAD

**Issue by fernandohcorrea** [OriginalMy/originalmy-readthedocs#18]
http://staging.originalmy.com/bitregistro/db83de4d5aee45632339d923e8d0ad8bbd3b331d65b249ff07c30fbe00e0003b

19. Da Lista de Mudanças

Atualizar Imagem em :
http://originalmy.readthedocs.io/pt_BR/latest/21-registro.html#criando-o-bitregistro

**Comment by romanonatacha** [comment]
close #16
